spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/kirank2005/eks-blueprints-workloads/
    targetRevision: main
  ingress:
    host: dev.example.com
